steps:
  - name: google/cloud-sdk:alpine
    entrypoint: 'bash'
    args:
      - 'gcloud'
      - 'dataflow'
      - 'flex-template'
      - 'run'
      - 'etl-dataflow-${_VERSION}-$(date +%Y%m%d-%H%M%S)'
      - '--template-file-gcs-location=gs://dataflow-bucket-quickstart/flex-template/etl-dataflow-flex-template.json'
      - '--parameters-from-file=gs://dataflow-bucket-quickstart/pipeline-options/pipeline-options.json'
      - '--temp-location=gs://dataflow-bucket-quickstart/etl-dataflow/temp'
      - '--staging-location=gs://dataflow-bucket-quickstart/etl-dataflow/staging'
      - '--num-workers=1'
      - '--max-workers=1'
      - '--region=us-central1'
      - '--worker-machine-type=e2-standard-2'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _VERSION: '1.1.0-SNAPSHOT'